// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtV-md2ich_C1HJN1m3h2MvQprUuK6Qw',
    appId: '1:210452997218:web:e8d33392968d590bb25d3b',
    messagingSenderId: '210452997218',
    projectId: 'fitroute-c1ce9',
    authDomain: 'fitroute-c1ce9.firebaseapp.com',
    storageBucket: 'fitroute-c1ce9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKKUeSZj42AbIiB3DVp_iihTdze2vc7sU',
    appId: '1:210452997218:android:e9bff6325ed6c2dbb25d3b',
    messagingSenderId: '210452997218',
    projectId: 'fitroute-c1ce9',
    storageBucket: 'fitroute-c1ce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdtS8z75YY_auQmEM72kB5MGBNXthWYo',
    appId: '1:210452997218:ios:40be8a758eaeba83b25d3b',
    messagingSenderId: '210452997218',
    projectId: 'fitroute-c1ce9',
    storageBucket: 'fitroute-c1ce9.firebasestorage.app',
    iosBundleId: 'com.example.fitRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZdtS8z75YY_auQmEM72kB5MGBNXthWYo',
    appId: '1:210452997218:ios:40be8a758eaeba83b25d3b',
    messagingSenderId: '210452997218',
    projectId: 'fitroute-c1ce9',
    storageBucket: 'fitroute-c1ce9.firebasestorage.app',
    iosBundleId: 'com.example.fitRoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQtV-md2ich_C1HJN1m3h2MvQprUuK6Qw',
    appId: '1:210452997218:web:36619832f74548cfb25d3b',
    messagingSenderId: '210452997218',
    projectId: 'fitroute-c1ce9',
    authDomain: 'fitroute-c1ce9.firebaseapp.com',
    storageBucket: 'fitroute-c1ce9.firebasestorage.app',
  );
}
